### ISSUE TITLE
Erreurs sur les fichiers

### ISSUE THREAD

**Issue by bernard-ng** [Gracielvie-Nzumba/Formation#1]
Tes fichiers de TPs n'ont pas la bonne extension, as-tu essayé d'exécuter?

**Comment by Gracielvie-Nzumba** [comment]
Oui j'ai essayé et ça marche chez moi, mais si c'est le cas vous me conseillez de faire comment ? Reprendre ou bien...?

**Comment by bernard-ng** [comment]
Rajoute l’extension .php à chacun de ces fichiers et respecte le nommage
décrit dans la spécification psr-12, pas besoin de recommencer juste mieux
organiser

**Comment by Gracielvie-Nzumba** [comment]
Merci. Je crois avoir fait ce que vous m'aviez demandé de faire, essayez de revoir si mes modifications sont bien faites.
